# Generated by Django 5.2.7 on 2025-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
